export const volunteersData = [
  {
    id: 1,
    name: 'Alice Wanjiku',
    location: 'Nairobi, Kenya',
    email: 'alice.w@email.com',
    phone: '+254 712 345 678',
    experience: '2 years with local NGOs',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Community Outreach, Event Planning',
    appliedDate: '2024-01-15',
    status: 'pending',
  },
  {
    id: 2,
    name: 'John Kamau',
    location: 'Mombasa, Kenya',
    email: 'jkamau@email.com',
    phone: '+254 723 456 789',
    experience: '3 years in youth mentorship',
    availability: 'Flexible',
    type: 'Remote Volunteer',
    skills: 'Teaching, Program Coordination',
    appliedDate: '2024-01-14',
    status: 'approved',
  },
  {
    id: 3,
    name: 'Grace Achieng',
    location: 'Kisumu, Kenya',
    email: 'grace.a@email.com',
    phone: '+254 734 567 890',
    experience: '1 year in community development',
    availability: 'Weekdays',
    type: 'Local Volunteer',
    skills: 'Project Management, Communication',
    appliedDate: '2024-01-13',
    status: 'approved',
  },
  {
    id: 4,
    name: 'Daniel Ochieng',
    location: 'Eldoret, Kenya',
    email: 'daniel.o@email.com',
    phone: '+254 745 678 901',
    experience: '6 months in digital marketing',
    availability: 'Evenings',
    type: 'Online Volunteer',
    skills: 'Social Media, Content Creation',
    appliedDate: '2024-01-12',
    status: 'pending',
  },
  {
    id: 5,
    name: 'Mary Njeri',
    location: 'Nakuru, Kenya',
    email: 'mary.n@email.com',
    phone: '+254 756 789 012',
    experience: '4 years in healthcare',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Health Education, First Aid',
    appliedDate: '2024-01-11',
    status: 'rejected',
  },
  {
    id: 6,
    name: 'Peter Mutua',
    location: 'Thika, Kenya',
    email: 'peter.m@email.com',
    phone: '+254 767 890 123',
    experience: '2 years in IT support',
    availability: 'Flexible',
    type: 'Remote Volunteer',
    skills: 'Technical Support, Training',
    appliedDate: '2024-01-10',
    status: 'approved',
  },
  {
    id: 7,
    name: 'Sarah Wambui',
    location: 'Nyeri, Kenya',
    email: 'sarah.w@email.com',
    phone: '+254 778 901 234',
    experience: '1 year in environmental conservation',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Environmental Advocacy, Research',
    appliedDate: '2024-01-09',
    status: 'pending',
  },
  {
    id: 8,
    name: 'David Kiprop',
    location: 'Kakamega, Kenya',
    email: 'david.k@email.com',
    phone: '+254 789 012 345',
    experience: '5 years in education',
    availability: 'Weekdays',
    type: 'Remote Volunteer',
    skills: 'Curriculum Development, Tutoring',
    appliedDate: '2024-01-08',
    status: 'approved',
  },
  {
    id: 9,
    name: 'Ruth Muthoni',
    location: 'Machakos, Kenya',
    email: 'ruth.m@email.com',
    phone: '+254 790 123 456',
    experience: '3 years in fundraising',
    availability: 'Flexible',
    type: 'Online Volunteer',
    skills: 'Grant Writing, Donor Relations',
    appliedDate: '2024-01-07',
    status: 'rejected',
  },
  {
    id: 10,
    name: 'James Kipchoge',
    location: 'Kericho, Kenya',
    email: 'james.k@email.com',
    phone: '+254 701 234 567',
    experience: '1 year in agriculture',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Farming, Sustainable Agriculture',
    appliedDate: '2024-01-06',
    status: 'approved',
  },
  {
    id: 11,
    name: 'Elizabeth Njoki',
    location: 'Nairobi, Kenya',
    email: 'elizabeth.n@email.com',
    phone: '+254 712 345 678',
    experience: '2 years in social work',
    availability: 'Weekdays',
    type: 'Local Volunteer',
    skills: 'Counseling, Case Management',
    appliedDate: '2024-01-05',
    status: 'pending',
  },
  {
    id: 12,
    name: 'Michael Otieno',
    location: 'Kisii, Kenya',
    email: 'michael.o@email.com',
    phone: '+254 723 456 789',
    experience: '4 years in youth sports',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Coaching, Team Building',
    appliedDate: '2024-01-04',
    status: 'pending',
  },
];
