export const mockApplications = [
  {
    id: 1,
    name: 'Alice Wanjiku',
    location: 'Nairobi, Kenya',
    email: 'alice.w@email.com',
    phone: '+254 712 345 678',
    experience: '2 years with local NGOs',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Community Outreach, Event Planning',
    appliedDate: '2024-01-15',
    status: 'pending',
  },
  {
    id: 2,
    name: 'John Kamau',
    location: 'Mombasa, Kenya',
    email: 'jkamau@email.com',
    phone: '+254 723 456 789',
    experience: '5 years in community development',
    availability: 'Flexible',
    type: 'Remote Volunteer',
    skills: 'Project Management, Fundraising',
    appliedDate: '2024-01-14',
    status: 'approved',
  },
  {
    id: 3,
    name: 'Grace Achieng',
    location: 'Kisumu, Kenya',
    email: 'grace.a@email.com',
    phone: '+254 734 567 890',
    experience: '3 years teaching experience',
    availability: 'Weekdays',
    type: 'Local Volunteer',
    skills: 'Education, Mentoring, Youth Programs',
    appliedDate: '2024-01-13',
    status: 'approved',
  },
  {
    id: 4,
    name: 'Daniel Ochieng',
    location: 'Eldoret, Kenya',
    email: 'daniel.o@email.com',
    phone: '+254 745 678 901',
    experience: '1 year volunteer experience',
    availability: 'Weekends',
    type: 'Online Volunteer',
    skills: 'Social Media Management, Content Creation',
    appliedDate: '2024-01-12',
    status: 'pending',
  },
  {
    id: 5,
    name: 'Sarah Muthoni',
    location: 'Nakuru, Kenya',
    email: 'sarah.m@email.com',
    phone: '+254 756 789 012',
    experience: 'No prior experience',
    availability: 'Evenings',
    type: 'Local Volunteer',
    skills: 'Communication, Teamwork',
    appliedDate: '2024-01-11',
    status: 'rejected',
  },
  {
    id: 6,
    name: 'Michael Otieno',
    location: 'Thika, Kenya',
    email: 'michael.o@email.com',
    phone: '+254 767 890 123',
    experience: '4 years in healthcare',
    availability: 'Full-time',
    type: 'Local Volunteer',
    skills: 'First Aid, Health Education, Patient Care',
    appliedDate: '2024-01-10',
    status: 'approved',
  },
  {
    id: 7,
    name: 'Faith Wangari',
    location: 'Nyeri, Kenya',
    email: 'faith.w@email.com',
    phone: '+254 778 901 234',
    experience: '2 years in environmental conservation',
    availability: 'Weekends',
    type: 'Remote Volunteer',
    skills: 'Environmental Advocacy, Research',
    appliedDate: '2024-01-09',
    status: 'pending',
  },
  {
    id: 8,
    name: 'Peter Karanja',
    location: 'Kiambu, Kenya',
    email: 'peter.k@email.com',
    phone: '+254 789 012 345',
    experience: '6 months volunteer work',
    availability: 'Flexible',
    type: 'Online Volunteer',
    skills: 'Graphic Design, Video Editing',
    appliedDate: '2024-01-08',
    status: 'rejected',
  },
  {
    id: 9,
    name: 'Lucy Njeri',
    location: 'Nairobi, Kenya',
    email: 'lucy.n@email.com',
    phone: '+254 790 123 456',
    experience: '3 years in social work',
    availability: 'Weekdays',
    type: 'Local Volunteer',
    skills: 'Counseling, Case Management',
    appliedDate: '2024-01-07',
    status: 'pending',
  },
  {
    id: 10,
    name: 'James Kipchoge',
    location: 'Kericho, Kenya',
    email: 'james.k@email.com',
    phone: '+254 701 234 567',
    experience: '1 year in agriculture',
    availability: 'Weekends',
    type: 'Local Volunteer',
    skills: 'Farming, Sustainable Agriculture',
    appliedDate: '2024-01-06',
    status: 'approved',
  },
];
